### ISSUE TITLE
GFA input

### ISSUE THREAD

**Issue by ekg** [th0mas-buechler/gedmap#1]
Do you have a mechanism to parse a GFA file into an EDS graph?

**Comment by thomas-buechler-ulm** [comment]
I am currently working on a method to parse the  HPRC graph. To work properly it will need to detect small 'bubbles' (e.g. SNP)  and encode them specially. I think I am able to release this function next month.

**Comment by thomas-buechler-ulm** [comment]
Ok, i did not well predict my time schedule, but now its there.
The latest commit added a mechanism to parse GFA files.
An explanation of the mechanism can temporary be found here: https://www.uni-ulm.de/fileadmin/website_uni_ulm/iui.inst.190/preprints/gedmap_update.pdf

You can run test with:
(in /a_little_example:) make ale_gfa 
(in /exp:) make gedmap_chm13_graph/run

**Comment by ekg** [comment]
Very cool! What kinds of graphs have you tested this on?

**Comment by thomas-buechler-ulm** [comment]
I used the graphs hprc-v1.0-mc-chm13.gfa and hprc-v1.0-mc-chm13.gfa.
