### ISSUE TITLE
cannot  generate            gedmap/human.geds

### ISSUE THREAD

**Issue by hphphpcat** [th0mas-buechler/gedmap#3]
excuse me , i wanted to do experiments to compare accuarcy between three mapper-tools which metioned in your paper,but something went wrong, i have downloaded data with your scripts in gedmap/data/Makefile,when i goto generate  gedmap/human.geds , it reported  error like ERROR: FA STREAM ENDED BEVOR SEQUENCE NEXT SEQUENCE WAS REACHED
GEDMAP PARSE                                           
the log is  in the following side ,can u help me to fix this problem thank u :)
.......................................................

Parse FA:                             ../data/hs37d5.fa

and  VCF:                             ../data/human.vcf

to  GEDS:                             gedmap/human.geds

.......................................................

Read VCF and FA and include eds-type variations        

READ SEQUENCE: 1 dna:chromosome chromosome:GRCh37:1:1:249250621:1

READ SEQUENCE: 2 dna:chromosome chromosome:GRCh37:2:1:243199373:1

READ SEQUENCE: 3 dna:chromosome chromosome:GRCh37:3:1:198022430:1

ERROR: UNEXPECTED SYMBOL: ASCII=(77)='M' IN FA at pos 562502027replaced by 'N'

ERROR: UNEXPECTED SYMBOL: ASCII=(82)='R' IN FA at pos 562502260replaced by 'N'

ERROR: UNEXPECTED SYMBOL: ASCII=(82)='R' IN FA at pos 562502261replaced by 'N'

READ SEQUENCE: 4 dna:chromosome chromosome:GRCh37:4:1:191154276:1

READ SEQUENCE: 5 dna:chromosome chromosome:GRCh37:5:1:180915260:1

READ SEQUENCE: 6 dna:chromosome chromosome:GRCh37:6:1:171115067:1

READ SEQUENCE: 7 dna:chromosome chromosome:GRCh37:7:1:159138663:1

READ SEQUENCE: 8 dna:chromosome chromosome:GRCh37:8:1:146364022:1

READ SEQUENCE: 9 dna:chromosome chromosome:GRCh37:9:1:141213431:1

READ SEQUENCE: 10 dna:chromosome chromosome:GRCh37:10:1:135534747:1

READ SEQUENCE: 11 dna:chromosome chromosome:GRCh37:11:1:135006516:1

READ SEQUENCE: 12 dna:chromosome chromosome:GRCh37:12:1:133851895:1

READ SEQUENCE: 13 dna:chromosome chromosome:GRCh37:13:1:115169878:1

READ SEQUENCE: 14 dna:chromosome chromosome:GRCh37:14:1:107349540:1

READ SEQUENCE: 15 dna:chromosome chromosome:GRCh37:15:1:102531392:1

READ SEQUENCE: 16 dna:chromosome chromosome:GRCh37:16:1:90354753:1

READ SEQUENCE: 17 dna:chromosome chromosome:GRCh37:17:1:81195210:1

READ SEQUENCE: 18 dna:chromosome chromosome:GRCh37:18:1:78077248:1

READ SEQUENCE: 19 dna:chromosome chromosome:GRCh37:19:1:59128983:1

READ SEQUENCE: 20 dna:chromosome chromosome:GRCh37:20:1:63025520:1

READ SEQUENCE: 21 dna:chromosome chromosome:GRCh37:21:1:48129895:1

READ SEQUENCE: 22 dna:chromosome chromosome:GRCh37:22:1:51304566:1

READ SEQUENCE: X dna:chromosome chromosome:GRCh37:X:1:155270560:1

READ SEQUENCE: Y dna:chromosome chromosome:GRCh37:Y:2649521:59034049:1

ERROR: FA STREAM ENDED BEVOR SEQUENCE NEXT SEQUENCE WAS REACHED
call '../gedmap -h' for help message
Command exited with non-zero status 1
	Command being timed: "../gedmap parse ../data/hs37d5.fa ../data/human.vcf -o gedmap/human.geds"
	User time (seconds): 94.42
	System time (seconds): 3.80
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:39.11
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 6756
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 715
	Voluntary context switches: 72
	Involuntary context switches: 171
	Swaps: 0
	File system inputs: 56
	File system outputs: 7528944
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1

**Comment by thomas-buechler-ulm** [comment]
Hi,

I tried to reproduce the error, but it works for me.
*** 
The error indicates that the FASTA and VCF files do not match. The sequence names should be identical in both files. 
***
**A guess of  what goes wrong in your test:**
I would expect, the  sequence names to be "1", "2", ... , "22", "X", and "Y".
The log, you provided , indicates that the sequence names in the FASTA file are:
"1 dna:chromosome chromosome:GRCh37:1:1:249250621:1",
"2 dna:chromosome chromosome:GRCh37:2:1:243199373:1",
 ... 
"Y dna:chromosome chromosome:GRCh37:Y:2649521:59034049:1".

The line 57 of file "data/Makefile" should normally cut the "dna:chromosome chromosome:GRCh37:1:1:249250621:1"-part of the sequence name. It seems to me that this does not work in your case.
***
**What you should try:** 
(a) Please check  the sequence names in the FASTA-file. 
For example use: 

`grep ">" data/hs37d5.fa`

To match the VFC file, the output should be:

> \>1
> \>2
> ...
> \>Y

(b) if the output is

> \>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
> ...

cut everything everything after the first word.
I did this by:
```
awk {'print $1'} data/hs37d5.fa > data/hs37d5.fa.new
mv data/hs37d5.fa.new data/hs37d5.fa
```
Check if it worked -> (a)
***
Let me know if this solves your problem.

**Comment by hphphpcat** [comment]
yeah,it solves my problem! Thank u a lot .

**Comment by hphphpcat** [comment]
another question , in your evaluation accuracy script ,I'm confused about why comparing the difference between start position from reference and alignment position for the constant value for 600 bp . Is that reasonable?

**Comment by hphphpcat** [comment]
and in your logic , you don't compare alignment's  the reference chromosome name and  simulate  chromosome name  , if they are't equal we cannot  regard this alignment is  a correct position hit.

**Comment by thomas-buechler-ulm** [comment]
I closed the issue because your fist question was solved.

> you don't compare alignment's the reference chromosome name

You are right. I added this check in the latest commit. (This actually wrongly classified  10 of  3.000.000 samples )

> why comparing the difference ....

I do not recommend to classify a alignment as 'correct' only if the positions are equal. There might be ambiguity in the alignment of the bases at the edge of the sample. Also e.g. hisat2 often applies clipping. The reported position then is the start of the partial alignment. Such 'correct' partial alignments would be lost. Also there might be differences (to vg) on how the positions is calculated, when the alignment uses the reverse complement of the sequences. 
Since I did not want to put the extra work in reconstructing the alignments (including the variation), I simply defined a threshold. (In my  experiments, this threshold was in favor the competitors, so i left it that way.)
However, you can set this threshold to 0 (or 1 in the previous version) to only count alignments with equal positions. 
On a further note, I think the alignments that are lost by changing the threshold, are interesting to look at, when trying to optimize any of the mentioned tools.

**Comment by hphphpcat** [comment]
awesome  ,furthermore I would like to know if there is a possibility in your algorithm that a false positive match will be produced when read mapping to a non-reference part.like a possible case that a path like an alignment chr1 index from 0 to 50~ variation part  from 0~100 , is this might be a hit in your solution?

**Comment by thomas-buechler-ulm** [comment]
i don't understand this question.

**Comment by hphphpcat** [comment]
that is false positive hit ,let's think a scenario  that your program output be an alignment that align on both non-variation part and variation part like for example chr1:from 0 to 100- variation chr1: from 0 to 50  but your program think this alignment is positive but in real it cannot be consider to be positive , I wonder if this error is possible.

**Comment by thomas-buechler-ulm** [comment]
Say the reference is `chr1 = xyz` and a variation is known:  "a instead of y". (with x, y, z, a  being strings).
The representation then is     `x(y|a)z `. A read will be then aligned to `xyz` and `xaz` and the better alignment will be reported. A _false postive_ alignment to the string `xyaz` will not be calculated.
