### ISSUE TITLE
another question

### ISSUE THREAD

**Issue by hphphpcat** [th0mas-buechler/gedmap#4]
another question , in your evaluation accuracy script ,I'm confused about why comparing the difference between start position from reference and alignment position for the constant value for 600 bp . Is that reasonable?
and in your logic , you don't compare alignment's the reference chromosome name and simulate chromosome name , if they are't equal we cannot regard this alignment is a correct position hit.

**Comment by thomas-buechler-ulm** [comment]
The answer is here: https://github.com/thomas-buechler-ulm/gedmap/issues/3#issuecomment-2203134327
