### ISSUE TITLE
How GBZ is generated？

### ISSUE THREAD

**Issue by yulufang** [th0mas-buechler/gedmap#5]
Hello author, by reading and learning your article, I came to github and wanted to download the code to execute it myself. I compiled GEDMAP according to the README document you provided, and when it was executed to giraffe, it was interrupted, I checked the Makefile document in the exp, which only references $gbz, and it was not generated, which caused it to not run later. If it is convenient for you, we hope to get your advice and guidance.
<img width="644" alt="Error" src="https://github.com/user-attachments/assets/8448b55e-ea87-4642-98c5-a06e5e3c7f18">

**Comment by thomas-buechler-ulm** [comment]
Hello,

first of all, i am no expert for **vg-tools**. For specific questions about vg/giraffe please consult https://github.com/vgteam/vg. 

That being said:

In my Makefile  `make giraffe/index.out` (see line 175--180 ) is used to generate the .gbz file.

It seems like you tried a different approach with the command: `vg autoindex --workflow giraffe -r ../data/hs37d5.fa  -v -p  -t 64`.
Thereby, the parameter for  -v  and -p are missing, what causes an error.  
_Note: Due to problems I did not use this command, and so it is commented out (line 171--173) in the Makefile.

**Comment by yulufang** [comment]
> Hello,
> 
> first of all, i am no expert for **vg-tools**. For specific questions about vg/giraffe please consult https://github.com/vgteam/vg.
> 
> That being said:
> 
> In my Makefile `make giraffe/index.out` (see line 175--180 ) is used to generate the .gbz file.
> 
> It seems like you tried a different approach with the command: `vg autoindex --workflow giraffe -r ../data/hs37d5.fa -v -p -t 64`. Thereby, the parameter for -v and -p are missing, what causes an error. _Note: Due to problems I did not use this command, and so it is commented out (line 171--173) in the Makefile.

**Comment by yulufang** [comment]
Thank you very much for your reply. But when I didn't try to build with this comment in the first place, i.e. when I compiled the whole experiment directly, I still had this problem: Couldn't open GBz file giraffe/human.giraffe.gbz. Thank you for your advice, and I still look forward to receiving some advice and guidance from you this time.
![new_error](https://github.com/user-attachments/assets/0bfd1a44-d747-49a1-8c9a-7490447a19bc)

**Comment by thomas-buechler-ulm** [comment]
In the folder **exp**: 

check if there is the file **giraffe/human.giraffe.gbz**

if not, try `rm -f giraffe/index.out; make giraffe/index.out`

check again. If the file was not generated please check the content of **giraffe/index.out**

-----

You also can run the experiments individually by:

`make gedmap/all`
`make gedmap/hisat2`
`make gedmap/minimap2` and
`make gedmap/giraffe`

This way the error in the execution of vg-giraffe does not prevent you from doing the other experiments.

**Comment by yulufang** [comment]
Thank you very much for your reply. I checked that there was no giraffe/human. giraffe.gbz file, and I followed your prompt to make giraffe/index. out, but make all still can't open the gbz file, causing the program to break. I'd like to ask you how to solve this.
<img width="602" alt="error1" src="https://github.com/user-attachments/assets/16960275-9193-4db2-9c1f-df4174322ff8">

**Comment by thomas-buechler-ulm** [comment]
I am guessing there is still no file **giraffe/human.giraffe.gbz** and the reason is probably written in the file **giraffe/index.out**.

**Comment by yulufang** [comment]
This is the generated giraffe/index.out, I still can't solve the problem of no gbz file, I would like to ask you to give some suggestions and guidance, thank you.
<img width="852" alt="four" src="https://github.com/user-attachments/assets/28ce1f57-9b62-4902-8475-37d2d81b328b">
<img width="853" alt="one" src="https://github.com/user-attachments/assets/a23f1fc0-7d6b-43a3-af42-71179cbbd79a">
<img width="857" alt="three" src="https://github.com/user-attachments/assets/94bb3e2a-4b45-4975-95f3-1493fd6685b4">
<img width="852" alt="two" src="https://github.com/user-attachments/assets/b73b1013-7d29-4055-b377-2e07477e91d1">

**Comment by thomas-buechler-ulm** [comment]
Look at line 94-98 the command `vg autoindex` was terminated by signal 9. 
This means your system killed the process. I cant help you with that; as I said before, I am not a developer of `vg`. Please confer https://github.com/vgteam/vg

**Comment by yulufang** [comment]
Okay, thank you sincerely for your help.
