### ISSUE TITLE
stoul error when using gedmap parse_gfa

### ISSUE THREAD

**Issue by NourMarzouka** [th0mas-buechler/gedmap#7]
When running the following command, I get **ERROR: stoul**
**gedmap parse_gfa graph.gfa** 
or
**gedmap parse_gfa graph.gfa -o graph.gedmap_parsed**
.......................................................
GEDMAP PARSE
.......................................................
Parse GFA:                           ERGP.minigraph.gfa
.......................................................
read gfa
count nodes
read nodes
**ERROR: stoul**
call 'gedmap -h' for help message

Any idea of the source of this error? Thanks!

**Comment by thomas-buechler-ulm** [comment]
I think the current implementation expects the segments to be numbered from 1 to n. 
I see if i can work on an updated version, that accepts any strings as >segment names<.

**Comment by thomas-buechler-ulm** [comment]
I made a commit that should fix this errors. If you still having troubles, please let me know.
